name: buildmodule

on:
  pull_request:
  workflow_dispatch:
    inputs:
      BUILD_TITLE:
        description: 'Custom Build Title'
        required: false
      KERNEL_TREE:
        description: 'Kernel Tree'
        default: 'https://github.com/Antaru74/kernel_xiaomi_peridot'
        required: true
      KERNEL_TREE_BRANCH:
        description: 'Kernel Tree Branch'
        required: true
        default: 'stable-r1'
      CODENAME:
        description: 'Phone Codename'
        default: 'peridot'
        required: true
      UPLOAD_TO_RELEASE:
        description: 'Upload to release'
        type: boolean
        default: false
      NOTIFY_START:
        description: 'Notify Build Start'
        type: boolean
        default: true
      NOTIFY_SUCCESS:
        description: 'Notify Build Success'
        type: boolean
        default: true
      TELEGRAM_CHAT_ID:
        description: 'Telegram Chat ID (optional)'
        required: false
      KERNELSU_OPTION:
        description: 'Choose KernelSU setup option (1: next, 2: next-susfs, 3: none)'
        required: true
        default: '1'
        type: choice
        options:
          - '1'
          - '2'
          - '3'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    environment: Telegram
    permissions:
      contents: write

    steps:
    - name: Display User Inputs
      run: |
        echo "::group::User Environment Variables"
        echo "Build Title: ${{ github.event.inputs.BUILD_TITLE }}"
        echo "Kernel Tree: ${{ github.event.inputs.KERNEL_TREE }}"
        echo "Branch: ${{ github.event.inputs.KERNEL_TREE_BRANCH }}"
        echo "Codename: ${{ github.event.inputs.CODENAME }}"
        echo "::endgroup::"

    - name: Notify Build Start
      if: ${{ github.event.inputs.NOTIFY_START == 'true' }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ github.event.inputs.TELEGRAM_CHAT_ID || secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: html
        message: |
          <b>🚀 Kernel MODULE Build Started</b>
          <b>Device</b>: <code>${{ github.event.inputs.CODENAME }}</code>

    - name: Generate Build Date
      id: build_date
      run: |
        echo "build_date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT

    - name: Initialize workspace
      id: workspace
      run: |
        mkdir workspace
        cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
        echo "build_title=${{ github.event.inputs.BUILD_TITLE || github.event.inputs.CODENAME }}" >> $GITHUB_OUTPUT

    - name: Prepare the build environment
      run: |
        sudo apt update -y
        sudo apt install -y flex bison libncurses-dev libssl-dev bc \
          build-essential git ccache binutils-aarch64-linux-gnu

        mkdir -p $HOME/tc
        cd $HOME/tc
        wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz -O clang.tar.gz
        mkdir clang
        tar -xf clang.tar.gz -C clang

    - name: Clone kernel source
      id: kernel
      working-directory: ${{ steps.workspace.outputs.workspace-folder }}
      run: |
        git clone --depth=1 \
          -b ${{ github.event.inputs.KERNEL_TREE_BRANCH }} \
          ${{ github.event.inputs.KERNEL_TREE }} kernel_tree
        echo "kernel-folder=$(pwd)/kernel_tree" >> $GITHUB_OUTPUT

    - name: Building kernel modules
      id: build
      working-directory: ${{ steps.kernel.outputs.kernel-folder }}
      run: |
        rm -rf KernelSU-Next

        if [[ "${{ github.event.inputs.KERNELSU_OPTION }}" == '1' ]]; then
          curl -LSs https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh | bash -s next
        elif [[ "${{ github.event.inputs.KERNELSU_OPTION }}" == '2' ]]; then
          curl -LSs https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh | bash -s next-susfs
        fi

        export PATH="$HOME/tc/clang/bin:$PATH"
        export LD_LIBRARY_PATH=$HOME/tc/clang/lib64:$LD_LIBRARY_PATH

        OUT_DIR=out
        DATE=$(date '+%Y%m%d-%H%M')
        VERSION="modules-${{ github.event.inputs.CODENAME }}-${DATE}"

        CORES=$(nproc)

        ARGS="ARCH=arm64 \
        O=${OUT_DIR} \
        CC=clang \
        LD=ld.lld \
        CLANG_TRIPLE=aarch64-linux-gnu- \
        CROSS_COMPILE=aarch64-linux-gnu- \
        CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
        -j${CORES}"

        make ${ARGS} peridot_defconfig
        make ${ARGS} olddefconfig
        make ${ARGS} modules

        mkdir modules_zip
        find ${OUT_DIR} -type f -name '*.ko' -exec cp --parents {} modules_zip/ \;

        cd modules_zip
        zip -r9 "../${VERSION}.zip" .
        cd ..

        echo "zipname=${VERSION}.zip" >> $GITHUB_OUTPUT

    - name: Upload to Release
      if: ${{ github.event.inputs.UPLOAD_TO_RELEASE == 'true' }}
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ steps.kernel.outputs.kernel-folder }}/${{ steps.build.outputs.zipname }}
        name: modules-${{ github.event.inputs.CODENAME }}-${{ steps.build_date.outputs.build_date }}
        tag_name: modules-${{ github.event.inputs.CODENAME }}-${{ steps.build_date.outputs.build_date }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Notify Build Success
      if: ${{ success() && github.event.inputs.NOTIFY_SUCCESS == 'true' }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ github.event.inputs.TELEGRAM_CHAT_ID || secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: html
        message: |
          <b>✅ Kernel MODULE Build Succeeded</b>
          <b>File</b>: <code>${{ steps.build.outputs.zipname }}</code>
